name: "Build"

on:
  push:

jobs:
  build-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: clone
        run: git clone https://github.com/suttacentral/suttacentral
      - name: cd into
        run: cd suttacentral
      - name: ls it
        run: ls -l


