name: "Build"

on:
  push:
    branches:
      - main

jobs:
  build-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            api/
            client/
          key: ${{ hashFiles('scripts/import.py', 'scripts/build-data.sh') }}
      - name: build the data
        if: steps.cache.outputs.cache-hit != 'true'
        run: sudo scripts/build-data.sh
      - name: zip the data
        run: sudo zip -r api.zip api
      - uses: actions/upload-artifact@v3
        with:
          name: sc-client
          path: client/
          retention-days: 5
      - uses: actions/upload-artifact@v3
        with:
          name: sc-api-data
          path: api.zip
          retention-days: 5

  build-redbean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache
        with:
          path: binaries/
          key: ${{ hashFiles('.redbean-version', 'scripts/build-redbean.sh') }}
      - name: build the data
        if: steps.cache.outputs.cache-hit != 'true'
        run: scripts/build-redbean.sh
      - uses: actions/upload-artifact@v3
        with:
          name: redbean-binaries
          path: binaries/
          retention-days: 5

  bundle:
    runs-on: ubuntu-latest
    needs: ["build-data", "build-redbean"]
    steps:
      - uses: actions/checkout@v3
      - name: get data
        uses: actions/download-artifact@v3
        with:
          name: redbean-binaries
          path: binaries
      - name: get data 2
        uses: actions/download-artifact@v3
        with:
          name: sc-api-data
      - name: get data 3
        uses: actions/download-artifact@v3
        with:
          name: sc-client
          path: client
      - name: package it
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install --user beautifulsoup4
          unzip api.zip
          scripts/create_search_index.py
          mv binaries/redbean.com .

          cp redbean.com "sc-portable_${GITHUB_REF_NAME}_en.com"
          cp redbean.com "sc-portable_${GITHUB_REF_NAME}_en_nosearch.com"
        
          scripts/package.sh "en" "sc-portable_${GITHUB_REF_NAME}_en_nosearch.com"
          scripts/package.sh "en" "sc-portable_${GITHUB_REF_NAME}_en.com"

          zip "sc-portable_${GITHUB_REF_NAME}_en.com" search.db
      - uses: actions/upload-artifact@v3
        with:
          name: sc-portable
          path: "*.com"
          retention-days: 5
  
  deploy:
    runs-on: ubuntu-latest
    needs: ["bundle"]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'production'
      - name: get data 2
        uses: actions/download-artifact@v3
        with:
          name: sc-portable
      - name: get docs
        uses: actions/download-artifact@v3
        with:
          name: docs
      - name: build docs
        run: |
          git checkout ${GITHUB_REF_NAME} -- docs
          tree
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install --user mkdocs-material
          python3 scripts/create_docs_table.py
          cd docs/
          mkdocs build
          mkdir -p site/builds
          cd ..
          find . -maxdepth 1 -name "sc_portable*.com" -exec mv {} docs/site/builds/
          find docs -maxdepth 1 -exec mv {} .
          rm -rf docs
      - name: push prod
        run: |
          git config --global user.name "Push Bot"
          git config --global user.email "olastor@users.noreply.github.com"
          git remote set-url origin "https://${{ secrets.GITHUB_TOKEN }}@github.com/olastor/sc-portable.git"
          git add -A
          git commit -m "deploy"
          git push
