name: "Build"

on:
  push:
    branches:
      - main

jobs:
  # build-docs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: build docs
  #       run: |
  #         pip3 install --user mkdocs-material
  #         cd docs
  #         mkdocs build
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: binaries
  #         path: binaries/
  #         retention-days: 5

  build-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            api/
            client/
          key: ${{ hashFiles('scripts/import.py', 'scripts/build-data.sh') }}
      - name: build the data
        if: steps.cache.outputs.cache-hit != 'true'
        run: sudo scripts/build-data.sh
      - name: zip the data
        run: sudo zip -r api.zip api
      - uses: actions/upload-artifact@v3
        with:
          name: sc-client
          path: client/
          retention-days: 5
      - uses: actions/upload-artifact@v3
        with:
          name: sc-api-data
          path: api.zip
          retention-days: 5

  build-redbean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache
        with:
          path: binaries/
          key: ${{ hashFiles('.redbean-version', 'scripts/build-redbean.sh') }}
      - name: build the data
        if: steps.cache.outputs.cache-hit != 'true'
        run: scripts/build-redbean.sh
      - uses: actions/upload-artifact@v3
        with:
          name: redbean-binaries
          path: binaries/
          retention-days: 5

  bundle:
    runs-on: ubuntu-latest
    needs: ["build-data", "build-redbean"]
    steps:
      - uses: actions/checkout@v3
      - name: get data
        uses: actions/download-artifact@v3
        with:
          name: redbean-binaries
      - name: get data 2
        uses: actions/download-artifact@v3
        with:
          name: sc-api-data
      - name: get data 3
        uses: actions/download-artifact@v3
        with:
          name: sc-client
      - name: package it
        run: |
          unzip api.zip
          mv binaries/redbean.com .
          scripts/package.sh "en" "redbean.com"
      - uses: actions/upload-artifact@v3
        with:
          name: result
          path: redbean.com
          retention-days: 5
